### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [RiaJ16/H-Tech_SIG#4]
In the README you mention that the plugin is specific to Windows. Is it so?

**Comment by RiaJ16** [comment]
El 27-06-2019 02:24, mazano escribió:

> In the README you mention that the plugin is specific to Windows. Is it so? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

It is since I haven't tested it in Linux.

-- 
Ing. en C. Jair Nájera Salaices 

Links:
------
[1]
https://github.com/RiaJ16/H-Tech_SIG/issues/4?email_source=notifications&amp;email_token=ADBPQZM3Q33T3QFDJ7I4NG3P4RTJHA5CNFSM4H3Y65H2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G372KCA
[2]

**Comment by pcav** [comment]
Please have someone test it. We strongly prefer multiplatform plugins.
Thanks.

**Comment by RiaJ16** [comment]
Will do, thanks
